// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB85ZQmJ2iy5jC5jwCtvo5dGLgb5lsUyPQ',
    appId: '1:520942184590:web:2e5f905000e2ba485e81df',
    messagingSenderId: '520942184590',
    projectId: 'vecinoapp-41341',
    authDomain: 'vecinoapp-41341.firebaseapp.com',
    storageBucket: 'vecinoapp-41341.firebasestorage.app',
    measurementId: 'G-09ESLM1LB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfCNhq0TMIlLB5ufPXS6lLI2FHqAfRt9I',
    appId: '1:520942184590:android:877b49702efb71ef5e81df',
    messagingSenderId: '520942184590',
    projectId: 'vecinoapp-41341',
    storageBucket: 'vecinoapp-41341.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhwNmPxpt82Byqpdd7D-uE5_WF4r8r2iw',
    appId: '1:520942184590:ios:929d3f9fafd42e085e81df',
    messagingSenderId: '520942184590',
    projectId: 'vecinoapp-41341',
    storageBucket: 'vecinoapp-41341.firebasestorage.app',
    iosBundleId: 'com.example.vecinoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhwNmPxpt82Byqpdd7D-uE5_WF4r8r2iw',
    appId: '1:520942184590:ios:929d3f9fafd42e085e81df',
    messagingSenderId: '520942184590',
    projectId: 'vecinoapp-41341',
    storageBucket: 'vecinoapp-41341.firebasestorage.app',
    iosBundleId: 'com.example.vecinoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB85ZQmJ2iy5jC5jwCtvo5dGLgb5lsUyPQ',
    appId: '1:520942184590:web:e3b52011d08271f55e81df',
    messagingSenderId: '520942184590',
    projectId: 'vecinoapp-41341',
    authDomain: 'vecinoapp-41341.firebaseapp.com',
    storageBucket: 'vecinoapp-41341.firebasestorage.app',
    measurementId: 'G-L58CMZJRT5',
  );
}
